In [4]:
import pandas as pd
import numpy as np
import re
import pickle

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [13]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\R M\Desktop\SEM 6\Financial news sentiment analysis\notebooks
['.ipynb_checkpoints', 'train_model.ipynb', 'Untitled.ipynb']

In [14]:
import os

print(os.listdir(".."))

['app', 'dataset', 'model', 'notebooks']

In [15]:
import os

print(os.path.exists("../dataset/all-data.csv"))

True

In [16]:
df = pd.read_csv(
    "../dataset/all-data.csv",
    names=["sentiment", "news"],
    encoding="latin-1"
)

df.head()

  sentiment                                               news
0   neutral  According to Gran , the company has no plans t...
1   neutral  Technopolis plans to develop in stages an area...
2  negative  The international electronic industry company ...
3  positive  With the new production plant the company woul...
4  positive  According to the company 's updated strategy f...

In [19]:
print(df.shape)

print(df["sentiment"].value_counts())

(4846, 2)
sentiment
neutral     2879
positive    1363
negative     604
Name: count, dtype: int64

In [20]:
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z ]', '', text)

    return text

In [21]:
df["clean_news"] = df["news"].apply(clean_text)

df.head()

,sentiment,news,clean_news
0,neutral,"According to Gran , the company has no plans t...",according to gran the company has no plans to...
1,neutral,Technopolis plans to develop in stages an area...,technopolis plans to develop in stages an area...
2,negative,The international electronic industry company ...,the international electronic industry company ...
3,positive,With the new production plant the company woul...,with the new production plant the company woul...
4,positive,According to the company 's updated strategy f...,according to the company s updated strategy fo...

In [22]:
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["clean_news"])

In [23]:
print(X.shape)

(4846, 5000)

In [24]:
encoder = LabelEncoder()

y = encoder.fit_transform(df["sentiment"])

print(encoder.classes_)

['negative' 'neutral' 'positive']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [26]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy =", accuracy)

Accuracy = 0.7670103092783506

In [28]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.92      0.50      0.65       110
           1       0.75      0.95      0.84       571
           2       0.80      0.50      0.62       289

    accuracy                           0.77       970
   macro avg       0.82      0.65      0.70       970
weighted avg       0.78      0.77      0.75       970